### ISSUE TITLE
Creating links in TrackScheme with "L"

### ISSUE THREAD

**Issue by nelas** [fiji/MaMuT#12]
Hi! It seems that the keyboard shortcut "L" (create a link between two spots) does not work on the TrackScheme window. I need to switch to the MaMuT viewer, press "L" and switch back to TrackScheme window. Is this expected?

**Comment by tinevez** [comment]
No, not at all. 
I cannot reproduce the bug on windows 10. What platform are you using? 
Are you sure that exactly two spots are selected before pressing the L key? Or are you in auto-linking mode?

**Comment by nelas** [comment]
I'm on Linux (Ubuntu 16.04). I'm selecting 2 spots with shift and pressing L. Nothing happens unless I alt-tab to the viewer, where pressing L links the two spots as expected.

**Comment by tinevez** [comment]
Ok I will have to ask for help for this because I cannot reproduce. 
We had a training course last week on MaMuT and all students had a Linux machine and the bug did not happen. There something weird here - if you have access to another Linux machine, can you try there?

**Comment by nelas** [comment]
Just tested on 3 different linux machines and they behave the same:

- Ubuntu GNOME 16.04, Linux kernel 4.4.0-51-generic
- Ubuntu elementaryOS 14.04, Linux kernel 4.4.0.47-generic
- Ubuntu 15.10, Linux kernel 4.2.0-34-generic

All running (Fiji) ImageJ 2.0.0-rc-54/1.51h; Java 1.8.0_66 [64-bit]

Steps:

1. Load MaMuT file.
2. Open TrackScheme and MaMuT Viewer.
3. Double click on viewer to create spot.
4. Forward 2 frames and create another spot.
5. TrackScheme now shows both unlaid spots. I click on the track to unselect the second spot.
6. Then, I select the first spot, hold shift and select the second spot.
7. Both spots are selected. I press L key: nothing happens.
8. I alt-tab to the viewer (spots are highlighted) and press L key: link is created.

Let me know if you need more infos!

**Comment by tinevez** [comment]
Ah ok I understood!

There is NO keyboard shortcut to create a link in TrackScheme. This is not a bug, this is an absence of feature.

**Comment by tinevez** [comment]
Sorry I am so slow, I missed the 'TrackScheme' window you put in your description.
Had I read it more cautiously I would have save you some time.

**Comment by nelas** [comment]
No problem :)
