### ISSUE TITLE
Add intermediate spots to existing edge

### ISSUE THREAD

**Issue by nelas** [fiji/MaMuT#13]
Is there a way to add intermediate spots along an existing edge (area highlighted in the black rectangle)?

![screenshot from 2016-11-24 22-55-46](https://cloud.githubusercontent.com/assets/361179/20789857/4da3e5aa-b7b6-11e6-89a0-ccb5baa0e33e.jpg)

After some trying, the quickest way I found was to:

1. Turn auto-linking on.
2. Select top cell.
3. Go through frames adding auto-linked spots.
4. When the bottom cell appears on the viewer, shift-click to select it with previous and press L key to link.
5. Go to TrackScheme, click the previous edge and delete it.
6. Refresh layout.

Is there a quicker or an official way to do it?

Cheers

**Comment by tinevez** [comment]
Yes there is an action in TrackMate that does this. I can import it to MaMuT for the next release.
