### ISSUE TITLE
Launch new and Load commands

### ISSUE THREAD

**Issue by nelas** [fiji/MaMuT#15]
Hi, the first time I used MaMuT I was confused with the names of the two commands:

- "Launch new MaMuT annotation"
- "Load MaMuT file"

`Launch` and `Load` are different words for the same action and `annotation` and `file` are also two words for the same thing. It might be clearer if the commands were something like this:

- "New MaMuT annotation"
- "Open MaMuT annotation"

Pretty minor issue, but maybe it helps.
Cheers

**Comment by tinevez** [comment]
Noted!
