### ISSUE TITLE
Persistent display settings

### ISSUE THREAD

**Issue by nelas** [fiji/MaMuT#16]
Hello

The display options such as spot radius, track display mode and "color by" are not persistent. These settings are lost after saving, closing and re-opening the MaMuT file.

Is there a way to save the current state of display options? If these display options can be loaded from file (instead of having to manually adjust every restart), it would be very handy for exporting movies with diverse colorschemes that highlight different aspects of the lineage.

Cheers,
Bruno

**Comment by tinevez** [comment]
Hi Bruno.
We don't plan on doing it for MaMuT, but in Mastodon instead.

**Comment by nelas** [comment]
Ok, thanks! Is Mastodon available for testing?

**Comment by tinevez** [comment]
Not yet sorry.
