### ISSUE TITLE
Large spot IDs collapse to same value

### ISSUE THREAD

**Issue by funkey** [fiji/MaMuT#19]
When I tried to open an annotation XML created by another script (i.e., not by manual annotations within MaMuT), only one "Spot" per frame was shown, although the XML file contains a few hundred per frame. The problem seems to be the use of large IDs. My annotation XML contains spots with:

```
        <Spot ID="19152000001" ...  />
        <Spot ID="19152000002" ... />
        <Spot ID="19152000003" ...  /> 
        ...
```
By changing the IDs to
```
        <Spot ID="1000001" ...  />
        <Spot ID="1000002" ... />
        <Spot ID="1000003" ...  /> 
        ...
```
I can see all spots as expected. I suspect that somewhere during reading of the XML, the IDs get converted to `float32`, causing collapsing of similar large values:

```
In [3]: int(np.float32(19152000001))
Out[3]: 19152001024

In [4]: int(np.float32(19152000002))
Out[4]: 19152001024

In [5]: int(np.float32(19152000003))
Out[5]: 19152001024

In [6]: int(np.float32(1000001))
Out[6]: 1000001

In [7]: int(np.float32(1000002))
Out[7]: 1000002

In [8]: int(np.float32(1000003))
Out[8]: 1000003
```

**Comment by tinevez** [comment]
Hummm the IDs get converted to `double` (or `float64`?) normally, so we normally have access to the whole range of `int`s. Do your IDs go beyond 2 billions?

**Comment by axtimwalde** [comment]
Hi @tinevez, yes the ids are above 2bio, as shown in the example above where they are at 19bio.  Is that illegal?  I.e. how hard is it to use long for the ids instead of doubles?

**Comment by tinevez** [comment]
I think I would have to rewrite the TrackMate model, because all ids are int :(

And I am afraid we did not attend to that problem in Mastodon, where we have this cap too.
Am I correct @tpietzsch ? I seem to remember you discuss using `long` instead of `int` in another use of `mastodon-collection` discussing with Philip/

**Comment by tpietzsch** [comment]
just to clarify: I'm talking about Mastodon. Not sure what would need to happen in MaMuT.

**Comment by tinevez** [comment]
For MaMuT and TrackMate I made the mistake of indexing spots in lists. So their max number is bound by int values :/

**Comment by tinevez** [comment]
So yes I would go to Mastodon which in my humble opinion is superior.

**Comment by tinevez** [comment]
Actually we also use `int` IDs in Mastodon. See:
https://github.com/bigdataviewer/mastodon-graph/blob/master/src/main/java/org/mastodon/graph/GraphIdBimap.java

**Comment by tpietzsch** [comment]
Yes, as I said accommodating > 2bio spots is a bigger task.
But supporting long IDs in imported XML files is easy. They will anyway get new internal IDs assigned. It's just about making sure the long IDs survive until the import is complete (which is easy).

**Comment by tinevez** [comment]
I am closing this issue for now, as MaMuT will not be able to harness it.
