### ISSUE TITLE
Import of TGMM results fails

### ISSUE THREAD

**Issue by bernhardw13** [fiji/MaMuT#20]
When I import results from TGMM to MaMuT, the plugin does so without showing any error message. Indeed the spots locations are imported correctly (see 1st screenshot). However, the tracks are very "chaotic". It seems like the wrong spots are connected. I then went back to the xml-files from TGMM to check if this was causing trouble. Nevertheless, when plotting these tracks with MATLAB they are fine (see 2nd screenshot). I'm using MaMuT version 0.28.0.
![failedtgmmimport](https://user-images.githubusercontent.com/30179803/45091366-7e391d00-b112-11e8-85a5-bb1c00a83ecb.png)
![howitshouldlooklike](https://user-images.githubusercontent.com/30179803/45091517-028ba000-b113-11e8-9dcc-3338301c58a7.png)

**Comment by tinevez** [comment]
Argh.
Can you share the TGMM files? Just the files for now, we will see if I can manage without the image.

**Comment by bernhardw13** [comment]
Thanks for the fast response!
Yes, the TGMM xml-files are attached to this post.
[TGMMxmlfiles.zip](https://github.com/fiji/MaMuT/files/2352798/TGMMxmlfiles.zip)

**Comment by tinevez** [comment]
It looks good to me and the results are gorgeous!
![mamutimport](https://user-images.githubusercontent.com/3583203/45096411-ce1ee080-b120-11e8-8ed6-2f67a1374f42.png)

I did this with the currently developed version though. It has as fix from @ksugar . I will upload it to Fiji soon and ask you to test it.

**Comment by bernhardw13** [comment]
This looks really good. Looking forward to the next version!

**Comment by tinevez** [comment]
Ok done.
Can you upload now? You should get v0.28.3. 
Can you then tell us whether it works?

**Comment by bernhardw13** [comment]
I did the update. Now the import works!
Thanks :)
![correcttgmmimport](https://user-images.githubusercontent.com/30179803/45098744-ec3b0f80-b125-11e8-86b3-307c52569bf6.png)

**Comment by bernhardw13** [comment]
Yes, feel free to use it. You can acknoweledge me as Bernhard Wallmeyer.

**Comment by tinevez** [comment]
https://forum.image.sc/t/mamut-v0-28-3-released/19511
